### ISSUE TITLE
Max Channels?

### ISSUE THREAD

**Issue by waffi121** [Stadicus/guides#184]
hi community

my raspi runs over 4 months :) I have the maximum channels set to 15 and they are now full.

what will be the maximum upper limit?

Thank you!

**Comment by Stadicus** [comment]
I don't think that there is an upper limit to channels. However, you must open channels to other nodes, and fund them, to really increase the connectivity. Otherwise it's just a bit of a coincidence when other people connect to your node. 

A few channels should be fine, however. Better 5 well funded channels, than 50 small ones.

**Comment by waffi121** [comment]
all right. Thank you.
