### ISSUE TITLE
Updating lnd to ver 0.5 beta rc1

### ISSUE THREAD

**Issue by bbelo** [Stadicus/guides#185]
Hi, I've just copied steps from "Install LND" chapter and installed the newest version of LND. The system service now fails to start. 

> admin@raspberrypi:~` $ sudo systemctl status lnd
> ● lnd.service - LND Lightning Daemon
>    Loaded: loaded (/etc/systemd/system/lnd.service; enabled; vendor preset: enabled)
>    Active: activating (auto-restart) (Result: exit-code) since Wed 2018-08-29 11:47:55 CEST; 4s ago
>   Process: 1160 ExecStart=/usr/local/bin/lnd --externalip=${PUBLICIP} (code=exited, status=1/FAILURE)
>  Main PID: 1160 (code=exited, status=1/FAILURE)
> 
> Aug 29 11:47:55 raspberrypi systemd[1]: lnd.service: Unit entered failed state.
> Aug 29 11:47:55 raspberrypi systemd[1]: lnd.service: Failed with result `'exit-code'.

**Comment by Stadicus** [comment]
Can you provide a bit more information, please? Log files, config files...

**Comment by irekzielinski** [comment]
migration to 0.5rc1 is not trivial. 
Number of issues are already captured in #190 
I had to:
- make distinct port numbers in bitcoin.conf
- change macaroon location
- call lncli with extra parameter (for testnet operation)

**Comment by Stadicus** [comment]
I'll document the update once the final version 0.5 is out. Thanks for all the input and y'alls enthusiasm!

**Comment by lechatnieger** [comment]
i also, tried to upgrade, but when i restart lnd 
i receive the following error : 
set 15 18:41:41 BitcoinVenetoNode lnd[8890]: Attempting automatic RPC configuration to bitcoind
set 15 18:41:41 BitcoinVenetoNode systemd[1]: lnd.service: Main process exited, code=exited, status=1/FAILURE
set 15 18:41:41 BitcoinVenetoNode systemd[1]: lnd.service: Unit entered failed state.
set 15 18:41:41 BitcoinVenetoNode systemd[1]: lnd.service: Failed with result 'exit-code'.

maybe because of the macaroon file that are not recreated after the restart,

i can only find macaroon file in /home/bitcoin/.lnd and not in /home/bitcoin/.lnd/data/chain/bitcoin/testnet

**Comment by Stadicus** [comment]
Guide has been updated. Please let me know if you find any inconsistencies.
