### ISSUE TITLE
Soft shut-down script

### ISSUE THREAD

**Issue by perefeliu** [Stadicus/guides#230]
Hi! very nicely detailed guide. It can be followed by linux newbies like me. Congratulations.

I am having some doubts regarding the shutdown process. After restarting several times (using sudo shutdown -r now), the Bitcoind database gets corrupted (or at least I suppose it has been due to successive shut downs). I suppose that a more a soft shutdown will imply first lncli stop, then bitcoin-cli stop, and then shutdown -r now. Prior to that, maybe disable the services using sudo systemctl stop lnd/bitcoind.

Am I wrong? does "shutdown -r now" takes into account the safe shutdown of both services and the database may be corrupted for other reasons?

Thanks in advance.

**Comment by Stadicus** [comment]
Yes, the regular shutdown will stop all services gracefully, unless it comes up to a timeout. For bitcoind it's set to a comfortable 2 minutes, LND should be done in a second or two (timeout is 10 seconds). I always restart all my nodes this way, never had any issues due to that (may others for other reasons, though... :)
