### ISSUE TITLE
Any plans to dockerize this setup?

### ISSUE THREAD

**Issue by vmavromatis** [Stadicus/guides#28]

**Comment by Stadicus** [comment]
Not really, I kinda like tinkering and improving... :-) But feel free to give it a go!

**Comment by tek8us** [comment]
I like installing each part separately too to learn how each works and how to update each.  So much control is lost by using docker.  But right now I think Samurai Dojo and Whirlpool is dockerized so I am trying to tinker Raspibolt to work with Samourai's Dojo installed via docker.   Not successful so far because of some tor issue I am trying to figure out.  Bonus section on installing Samourai's Dojo into Raspibolt, maybe one day?
