### ISSUE TITLE
Restructuring/combining both guides

### ISSUE THREAD

**Issue by dennisreimann** [Stadicus/guides#312]
Hi, this issue is more of a question and asking for your opinion :)

The Raspibolt and Thundroid setups are similar for the most parts, especially when it comes to the general setup and instalation process of bitcoin/lnd.
To simplify the maintenance it might be worth considering to restructure and maybe combine parts of both guides. WHat do you think?

Background: I personally have the Odroid setup running, but I think most people are running the Raspibolt version – at least it seems like most of the issues and pull requests deall with the Raspi guide. I'd offer to help maintain the guide as I'm also trying to keep my Thundroid up to date and still use these guides as a reference.

**Comment by Stadicus** [comment]
Hej @dennisreimann, the fact that there are two guide is mostly because the Thundroid guide started as a standalone article for the Odroid Magazine. They are really almost identical and I was already thinking about merging them. 

The RaspiBolt guide should probably be the master guide, but I have also thought about writing a generic Ubuntu 18.04 LTS guide for usage with VPS & Odroid (the differences would be trivial).

Your help would be very much appreciated. What's your oppinion on how to best tackle this?

**Comment by dennisreimann** [comment]
I think the generic Ubuntu guide would male total sense and we could focus on the specialties of the particular devices on separate pages as it‘s done with the bonus chapters. 
The RaspiBolt guide would be the basis as you already suggested. In addition I‘d also suggest to deploy the guide to GitHub pages as it might provide a better reading experience and have proper navigation. 

The outstanding pull requests should get integrated first and after that we could go ahead and do the restructuring. As I said I could imagine doing that too.

**Comment by Stadicus** [comment]
Shoot me a DM on twitter to discuss.
