### ISSUE TITLE
Better explanation - Copy bitcoin.conf to user "admin" home  

### ISSUE THREAD

**Issue by Janaka-Steph** [Stadicus/guides#427]
Hello,

Thundroid guide recommend to copy bitcoin.conf to user "admin" home directory without explaining much the purpose of it. It would be nice to have a bit more explanation. 
Thank you
 
```
Copy bitcoin.conf to user "admin" home directory for RPC credentials
$ mkdir /home/admin/.bitcoin
$ sudo cp /home/bitcoin/.bitcoin/bitcoin.conf /home/admin/.bitcoin/
$ sudo chown admin:admin /home/admin/.bitcoin/bitcoin.conf
```

**Comment by daniel-vera-g** [comment]
Well I think `Copy bitcoin.conf to user "admin" home directory for RPC credentials` is enough explanation.

You do this after creating the service to autostart bitcoind. Since the bitcoin.conf belongs to the user bitcoin, but the user admin autostarts the bitcoind.service, the config file has to be copied over to the admin user.

If you still think it's not enough explanation, you can make a proposal of what should be added and I can make a PR for you.

**Comment by Janaka-Steph** [comment]
Hello, 
Thank you for your quick reply, I understand better know. I think what you just said would be a good addition "Since the bitcoin.conf belongs to the user bitcoin, but the user admin autostarts the bitcoind.service, the config file has to be copied over to the admin user."   
It's just a suggestion, I guess it's not clear for everybody but feel free to close the issue.

**Comment by daniel-vera-g** [comment]
I think it's enough. This issue can be a reference for people which don't understand it. Will leave @Stadicus the decision.

**Comment by Stadicus** [comment]
I have to admin that I am currently not working actively on the Thundroid guide. The RaspiBolt is basically the same, so you can always cross check there.
