### ISSUE TITLE
error: couldn't connect to server: unknown (code -1)

### ISSUE THREAD

**Issue by nperalez** [Stadicus/guides#61]
Hello,

First off, thank you so much for writing this. I'm not entirely new to running a full node as this is now my third time but I'm having the following problem:

When I run

$ systemctl status bitcoind.service

My screenshot seems to match yours
![image](https://user-images.githubusercontent.com/17304783/38973878-ade876e6-435c-11e8-845d-e7591e7ea022.png)

When I run the log command, it also seems to be downloading the testnet3 blocks:

$ sudo tail -f /home/bitcoin/.bitcoin/testnet3/debug.log
![image](https://user-images.githubusercontent.com/17304783/38973919-d5d0a57a-435c-11e8-80dd-9666a0d0dbea.png)

But when I follow the next step, I get the following error:
$ bitcoin-cli getblockchaininfo
> error: couldn't connect to server: unknown (code -1)
(make sure server is running and you are connecting to the correct RPC port)

From my limited experieince of running a node, this is usually because I have yet to run the command
# bitcoind -daemon

However, I can see the blocks downloading due to the service we created. Any ideas as to why I am getting this error? This is all from the admin user created through the tutorial.

**Comment by Stadicus** [comment]
The `bitcoind.service` takes care of starting the `bitcoind`, with the -daemon option specified in the configuration file. So that's not the issue, you never need to manually touch `bitcoind`, only `bitcoin-cli`.

It's possible that the system is just too busy to answer during the initial download of the blockchain. As long as it's downloading, you just need to wait for it to finish. 

Another option is that you did not copy the `bitcoin.conf` file into the `/home/admin/.bitcoin` directory of and thus the authentication fails.

**Comment by nperalez** [comment]
It seems to be working now. I think the problem was your later comment. That is, I forgot to copy the `bitcoin.conf file`. However, I thought this yesterday and copied it with no luck. I attempted the same thing today after reading your comment. The only thing I can remember doing different, at least I think, is that before I copied the file I stopped the bitcoind.service. After then restarting the pi it seemed to work. Thanks again!
