### ISSUE TITLE
Error on Electrum guide

### ISSUE THREAD

**Issue by Sowiedu** [Stadicus/guides#67]
./server.py leads to:

[https://imgur.com/cC6lZDr](https://imgur.com/cC6lZDr)

**Comment by Stadicus** [comment]
Not sure what causes this, might be a recent commit to Electrum Personal Server? 

Try to clone the latest release (tagged "v0.1.1") instead of the "master" branche
https://github.com/chris-belcher/electrum-personal-server/releases
https://stackoverflow.com/questions/791959/download-a-specific-tag-with-git

**Comment by Sowiedu** [comment]
Alright, will do tonight. Thanks for the pointer! I will report back.

**Comment by Sowiedu** [comment]
Alright, I did what you said and still get the same error. I noticed my mpk starts with a z instead of an x like in the sample. Is that an issue? Also I didn't put in any watch-only-adresses, but that shouldn't matter, right? only my mpk.

**Comment by Stadicus** [comment]
I just reinstalled the EPS last week from the master branch, it worked fine. If you still run into issues, I would recommend opening an issue on the https://github.com/chris-belcher/electrum-personal-server repository.
