### ISSUE TITLE
Channels are not being created?

### ISSUE THREAD

**Issue by feathertwigs** [Stadicus/guides#73]
I've followed the guide, (a lot of fun, thanks),
I've now been synced and running for 3 days (testnet). I'm unable to make payments and I can't workout what is wrong. 

Here is my 'getinfo' information:
 "alias": "YOUR_NAME [LND]",
    "num_pending_channels": 0,
    "num_active_channels": 0,
    "num_peers": 3,
    "block_height": 1311616,
    "block_hash": "0000000000035ba197ff3c9276f3452923fc868beef26cda780a6dd17e400aad",
    "synced_to_chain": true,
    "testnet": true,
    "chains": [
        "bitcoin"

**Here's the message I get when I try starblocks:**

 "payment_error": "unable to route payment to destination: UnknownNextPeer",
        "payment_preimage": "",
        "payment_route": null

**Here's the message I receive when I try Y'alls:**

        "payment_error": "unable to find a path to destination",
        "payment_preimage": "",
        "payment_route": null

**Comment by Cees2daBees** [comment]
You don't seem to have any payment channels created. Did you move some testnet bitcoin into your wallet? You can check your wallet balance and channel balance with
lncli walletbalance
lncli channelbalance

See also "Get some testnet bitcoin" section in
https://github.com/Stadicus/guides/blob/master/raspibolt/raspibolt_40_lnd.md

After wallet is funded with some testnet bitcoin, autopilot should start setting up payment channels.

**Comment by feathertwigs** [comment]
Thanks for taking the time to help me. I followed all the instructions in the guide, here is my wallet balance:

 "total_balance": "21999777",
    "confirmed_balance": "21999777",
    "unconfirmed_balance": "0"

is it too low, should I get more testnet coins?

**Comment by Cees2daBees** [comment]
you can try opening a channel manually with one of your peers.
you can get the peer info using 'lncli listpeers'
and to set up a channel see below:

# Attempt to open a new channel to an existing peer with the key node-key
# optionally blocking until the channel is 'open'.
# One can also connect to a node before opening a new channel to it by
# setting its host:port via the --connect argument. For this to work,
# the node_key must be provided, rather than the peer_id. This is optional.
# The channel will be initialized with local-amt satoshis local and push-amt
# satoshis for the remote node. Once the channel is open, a channelPoint (txid:vout)
# of the funding output is returned.
# One can manually set the fee to be used for the funding transaction via either
# the --conf_target or --sat_per_byte arguments. This is optional.

$ lncli openchannel [command options] node-key local-amt push-amt

# --node_key value       the identity public key of the target node/peer serialized in compressed format
# --connect value        (optional) the host:port of the target node
# --local_amt value      the number of satoshis the wallet should commit to the channel (default: 0)
# --push_amt value       the number of satoshis to push to the remote side as part of the initial commitment state (default: 0)
# --block                block and wait until the channel is fully open
# --conf_target value    (optional) the number of blocks that the transaction *should* confirm in, will be used for fee estimation (default: 0)
# --sat_per_byte value   (optional) a manual fee expressed in sat/byte that should be used when crafting the transaction (default: 0)
# --private              make the channel private, such that it won't be announced to the greater network, and nodes other than the two channel endpoints must be explicitly told about it to be able to route through it
# --min_htlc_msat value  (optional) the minimum value we will require for incoming HTLCs on the channel (default: 0)

**Comment by Stadicus** [comment]
You can check whether you have open and active channels with `lncli listchannels`. You should have 2+ channels with an online counterparty (active true/false) and enough outgoing liquidiy (local balance) for the payment you want to send. 

As suggested by @Cees2daBees you can always manually open a channel to a well-connected node like Y'alls (check https://explorer.acinq.co/#/ for peers).

**Comment by feathertwigs** [comment]
Thank you for the help, I've only just got back to this today. 

I went and acquired additional coins from the faucet. I've also been trying to lncli connect to as many peers as I can.

Anyway, I now have 5 peers and 2 active channels 👍
