### ISSUE TITLE
This question is concerning the raspibolt, please help!

### ISSUE THREAD

**Issue by Freefromchainz** [Stadicus/guides#78]
This question is concerning the raspibolt, please help!

issue with ip uri on test net explorer acinq showing all zeros and moving the locale, it is also clustered with 19 other nodes the nodes. Locale on the map should be north Carolina but it shows it off the coast of Africa @stadicus https://explorer.acinq.co/n/03013321192df9ccd975baf68436c451957aac1498b759a8f066ef51ca9339abfb

03013321192df9ccd975baf68436c451957aac1498b759a8f066ef51ca9339abfb@0:0:0:0:0:0:0:0:9735

Thanks!

**Comment by Stadicus** [comment]
The URI consists of tree distinct part:
* your public Node Key (03013321192...066ef51ca9339abfb)
* your IP address (something like 194.40.217.50)
* your port number (usually 9735)

Your URI does not contain a valid IP address, but 0:0:0:0:0:0:0:0 instead.

03013321192df9ccd975baf68436c451957aac1498b759a8f066ef51ca9339abfb@**0:0:0:0:0:0:0:0**:973

What is the output when you run the following commands on your RaspiBolt?  
```
$ curl ipinfo.io/ip
$  sudo systemctl status lnd
```

**Comment by zx9r** [comment]
Please attach here your /etc/systemd/system/lnd.service file

I think the problem can be there

**Comment by Moabbit** [comment]
@Stadicus i think we have followed all your suggestions, I have attached some screenshots. However, we're still in the same boat. The node is in the wrong location on the Explorer also the node is having issues connecting to others on the map. Any further suggestions?

![download_20180615_083350](https://user-images.githubusercontent.com/40186550/41476610-f06bcf80-7076-11e8-83ca-ea71e90a62f1.jpg)
![download_20180615_083356](https://user-images.githubusercontent.com/40186550/41476647-0dd6cf34-7077-11e8-847e-5e3b48446870.jpg)
![download_20180615_083350](https://user-images.githubusercontent.com/40186550/41476656-13f1a510-7077-11e8-9ba8-88658192f4f0.jpg)

**Comment by zx9r** [comment]
Instead of taking a screenshot of lnd.service file, please upload the file here as an attachment

**Comment by Moabbit** [comment]
@zx9r Im a first time user, how and why do that?

**Comment by zx9r** [comment]
I had similar problem with the --externalip and I think it could be the same. Need to review the file to be sure.

**Comment by Moabbit** [comment]
Thanks @zx9r I'll check it out and confirm.

**Comment by BitcoinVegan** [comment]
`# RaspiBolt LND Mainnet: systemd unit for lnd
# /etc/systemd/system/lnd.service

[Unit]
Description=LND Lightning Daemon
Wants=bitcoind.service
After=bitcoind.service

# for use with sendmail alert
#OnFailure=systemd-sendmail@%n

[Service]
# get var PUBIP from file
EnvironmentFile=/run/publicip

ExecStart=/usr/local/bin/lnd --externalip=108.248.221.82
PIDFile=/home/bitcoin/.lnd/lnd.pid
User=bitcoin
Group=bitcoin
LimitNOFILE=128000
Type=simple
KillMode=process
TimeoutSec=180
Restart=always
RestartSec=60

[Install]
WantedBy=multi-user.target
`

**Comment by Stadicus** [comment]
First, I think it's important to mention that the LN explorers are not crucial for your node to work. The present only one possible view of the network (they are just nodes themselves) and are frequently outdated.

More important is, that 
a) you can connect to other nodes, and for that you do not need to publish your IP address, and 
b) other nodes can connect to you (this means you need to announce your IP address to the network).

Now, if your IP address is correctly announced, it should be located somewhere here:
https://geoiptool.com/de/?ip=108.248.221.82

To cover the above mentioned basics, can you paste the output of the following commands? 
* `sudo systemctl status lnd`
* `bitcoin-cli -getinfo`
* `lncli getinfo`

**Comment by BitcoinVegan** [comment]
I will once I get home, thank you for this update.

**Comment by BitcoinVegan** [comment]
` lnd.service - LND Lightning Daemon
   Loaded: loaded (/etc/systemd/system/lnd.service; enabled; vendor preset: enab
   Active: activating (auto-restart) (Result: resources) since Sat 2018-06-16 15

Jun 16 15:54:42 bitcoinveganbolt systemd[1]: lnd.service: Unit entered failed st
Jun 16 15:54:42 bitcoinveganbolt systemd[1]: lnd.service: Failed with result 're
lines 1-6/6 (END)
`

**Comment by BitcoinVegan** [comment]
` lnd.service - LND Lightning Daemon
   Loaded: loaded (/etc/systemd/system/lnd.service; enabled; vendor preset: enab
   Active: activating (auto-restart) (Result: resources) since Sat 2018-06-16 15

Jun 16 15:54:42 bitcoinveganbolt systemd[1]: lnd.service: Unit entered failed st
Jun 16 15:54:42 bitcoinveganbolt systemd[1]: lnd.service: Failed with result 're
lines 1-6/6 (END)
`

**Comment by BitcoinVegan** [comment]
` bitcoin-cli -getinfo
error: couldn't connect to server: unknown (code -1)
(make sure server is running and you are connecting to the correct RPC port)
`

**Comment by BitcoinVegan** [comment]
` lncli getinfo
[lncli] rpc error: code = Unavailable desc = grpc: the connection is unavailable`

**Comment by BitcoinVegan** [comment]
` sudo systemctl status lnd
● lnd.service - LND Lightning Daemon
   Loaded: loaded (/etc/systemd/system/lnd.service; enabled; vendor preset: enab
   Active: activating (auto-restart) (Result: resources) since Sat 2018-06-16 16

Jun 16 16:00:44 bitcoinveganbolt systemd[1]: lnd.service: Failed to run 'start'
Jun 16 16:00:44 bitcoinveganbolt systemd[1]: Failed to start LND Lightning Daemo
Jun 16 16:00:44 bitcoinveganbolt systemd[1]: lnd.service: Unit entered failed st
Jun 16 16:00:44 bitcoinveganbolt systemd[1]: lnd.service: Failed with result 're
lines 1-8/8 (END)...skipping...
`

**Comment by BitcoinVegan** [comment]
should i put the public IP script back in, because I scraped it as you said in your earlier instructions?

**Comment by Stadicus** [comment]
Doesn't look too good. 

Is your `bitcoind` running with a synced chain? It does not look like it, so this is the first issue you need to look at. Make sure, user `admin` has access to the rpcpassword (by copying `bitcoin.conf` etc)
https://github.com/Stadicus/guides/blob/master/raspibolt/raspibolt_30_bitcoin.md#autostart-bitcoind

After this works, we can check if LND is working. And please make sure to provide the full output, all lines of the `systemctl status` are cut off at the right side, missing crucial information.

BTW, with three backticks (\```) you can create code blocks (I edited your post above).

**Comment by BitcoinVegan** [comment]
`# RaspiBolt LND Mainnet: systemd unit for bitcoind
# /etc/systemd/system/bitcoind.service

[Unit]
Description=Bitcoin daemon
Wants=getpublicip.service
After=getpublicip.service

# for use with sendmail alert (coming soon)
#OnFailure=systemd-sendmail@%n

[Service]
User=bitcoin
Group=bitcoin
Type=forking
PIDFile=/home/bitcoin/.bitcoin/bitcoind.pid
ExecStart=/usr/local/bin/bitcoind -daemon -conf=/home/bitcoin/.bitcoin/bitcoin.conf -pid=/home/bitcoin/.bitcoin/bitcoind.pid
KillMode=process
Restart=always
TimeoutSec=120
RestartSec=30

[Install]
WantedBy=multi-user.target`

**Comment by BitcoinVegan** [comment]
`systemctl status bitcoind.service
● bitcoind.service - Bitcoin daemon
   Loaded: loaded (/etc/systemd/system/bitcoind.service; enabled; vendor preset:
   Active: active (running) since Sat 2018-06-16 22:38:57 EDT; 2min 36s ago
  Process: 649 ExecStart=/usr/local/bin/bitcoind -daemon -conf=/home/bitcoin/.bi
 Main PID: 650 (bitcoind)
   CGroup: /system.slice/bitcoind.service
           └─650 /usr/local/bin/bitcoind -daemon -conf=/home/bitcoin/.bitcoin/bi`

**Comment by BitcoinVegan** [comment]
`sudo tail -f /home/bitcoin/.bitcoin/testnet3/debug.log
2018-06-17 02:41:46 New outbound peer connected: version: 70015, blocks=1325641, peer=14
2018-06-17 02:41:46 connect() to 159.65.96.207:18333 failed after select(): Connection refused (111)
2018-06-17 02:41:53 connect() to 219.91.248.99:18333 failed after select(): No route to host (113)
2018-06-17 02:42:00 New outbound peer connected: version: 70015, blocks=1325641, peer=17
2018-06-17 02:42:00 connect() to 5.39.130.240:18333 failed after select(): Connection refused (111)
2018-06-17 02:42:01 connect() to 167.99.165.151:18333 failed after select(): Connection refused (111)
2018-06-17 02:42:13 New outbound peer connected: version: 70015, blocks=1325641, peer=18
2018-06-17 02:42:13 New outbound peer connected: version: 70015, blocks=1325641, peer=19
2018-06-17 02:42:14 New outbound peer connected: version: 70015, blocks=1325641, peer=20
2018-06-17 02:42:14 New outbound peer connected: version: 70014, blocks=1325641, peer=21
2018-06-17 02:46:31 UpdateTip: new best=0000000000007d8e56a456bb24bb7e4d0f37de27836a3b4dca1d40bdc7535797 height=1325642 version=0x20000000 log2_work=70.32805 tx=18425899 date='2018-06-17 02:46:15' progress=1.000000 cache=0.0MiB(142txo) warning='5 of last 100 blocks have unexpected version'
`

**Comment by BitcoinVegan** [comment]
` bitcoin-cli getblockchaininfo
{
  "chain": "test",
  "blocks": 1325642,
  "headers": 1325642,
  "bestblockhash": "0000000000007d8e56a456bb24bb7e4d0f37de27836a3b4dca1d40bdc753                                                                             5797",
  "difficulty": 1,
  "mediantime": 1529197940,
  "verificationprogress": 0.9999995652859858,
  "initialblockdownload": false,
  "chainwork": "000000000000000000000000000000000000000000000050571670cc85225dc7                                                                             ",
  "size_on_disk": 13343888767,
  "pruned": false,
  "softforks": [
    {
      "id": "bip34",
      "version": 2,
      "reject": {
        "status": true
      }
    },
    {
      "id": "bip66",
      "version": 3,
      "reject": {
        "status": true
      }
    },
    {
      "id": "bip65",
      "version": 4,
      "reject": {
        "status": true
      }
    }
  ],
  "bip9_softforks": {
    "csv": {
      "status": "active",
      "startTime": 1456790400,
      "timeout": 1493596800,
      "since": 770112
    },
    "segwit": {
      "status": "active",
      "startTime": 1462060800,
      "timeout": 1493596800,
      "since": 834624
    }
  },
  "warnings": "Warning: unknown new rules activated (versionbit 28)"
`

**Comment by BitcoinVegan** [comment]
`sudo systemctl status lnd
● lnd.service - LND Lightning Daemon
   Loaded: loaded (/etc/systemd/system/lnd.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: resources) since Sat 2018-06-16 22:55:09 EDT; 23s ago

Jun 16 22:55:09 bitcoinveganbolt systemd[1]: Failed to start LND Lightning Daemon.
Jun 16 22:55:09 bitcoinveganbolt systemd[1]: lnd.service: Unit entered failed state.
Jun 16 22:55:09 bitcoinveganbolt systemd[1]: lnd.service: Failed with result 'resources'.
`

**Comment by BitcoinVegan** [comment]
`sudo systemctl status lnd
● lnd.service - LND Lightning Daemon
   Loaded: loaded (/etc/systemd/system/lnd.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: resources) since Sat 2018-06-16 22:55:09 EDT; 23s ago

Jun 16 22:55:09 bitcoinveganbolt systemd[1]: Failed to start LND Lightning Daemon.
Jun 16 22:55:09 bitcoinveganbolt systemd[1]: lnd.service: Unit entered failed state.
Jun 16 22:55:09 bitcoinveganbolt systemd[1]: lnd.service: Failed with result 'resources'.
`

**Comment by BitcoinVegan** [comment]
` sudo systemctl status lnd
● lnd.service - LND Lightning Daemon
   Loaded: loaded (/etc/systemd/system/lnd.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: resources) since Sat 2018-06-16 22:58:09 EDT; 14s ago

Jun 16 22:58:09 bitcoinveganbolt systemd[1]: Failed to start LND Lightning Daemon.
Jun 16 22:58:09 bitcoinveganbolt systemd[1]: lnd.service: Unit entered failed state.
Jun 16 22:58:09 bitcoinveganbolt systemd[1]: lnd.service: Failed with result 'resources'.`

**Comment by BitcoinVegan** [comment]
I was able to connect after rebuilding the public IP script.

**Comment by Stadicus** [comment]
It's hard to help if you cannot paste complete (non cut-off) information. And please take the time to format them correctly using the three backticks \```

So, does it work now?

**Comment by Moabbit** [comment]
@stadicus we were able to find the node on the link provided, connect the node to another on the testnet and fund a channel. Thank you for the assist. Cheers!

Pardon the botched paste job above.

**Comment by BitcoinVegan** [comment]
@Stadicus yes it does work thank you. I'm not sure what "cut off" you are referring to I copy and paste all I could that involved each particular code.

None the less with your steady guidance and instruction we were able to get everything squared away, and will definitely be reaching out to you in the future if another situation comes about.

**Comment by Stadicus** [comment]
Hej @BitcoinVegan, great to hear! With "cut off" I was referring to the right part of your cut/paste snippets, there was important information missing:

![2018-06-18 19_42_59-this question is concerning the raspibolt please help issue 78 stadicus_g](https://user-images.githubusercontent.com/19550140/41552990-bba38772-7330-11e8-895d-ef168e2525a2.png)

Don't hesitate to post again an issue if you run into issues.

**Comment by blockchaineur** [comment]
I guys I have this similar issue, could give the solution here please (like the bitcoin.conf final version of the file maybe?).
Thx

**Comment by Stadicus** [comment]
It's probably best if you open a new issue and describe it in as much detail as possible.
